package net.hasanguner.domain.lex

enum class DialogEvent {
    ALCOHOL_PREFERENCE_REQUESTED,
    ALCOHOL_PREFERENCE_CONFIRMED,
    CLARIFYING_COCKTAIL_CATEGORY,
    COCKTAIL_CATEGORY_REQUESTED,
    COCKTAIL_CATEGORY_CONFIRMED,
    COCKTAIL_PREFERENCE_REQUESTED,
    COCKTAIL_SERVED,
    REPEAT_ORDER_DECLINED,
    ASKED_FOR_REPEAT_ORDER,
}